<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7328" started-at="2019-01-23T12:32:03Z" finished-at="2019-01-23T12:32:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7328" started-at="2019-01-23T12:32:03Z" finished-at="2019-01-23T12:32:10Z">
      <class name="testCases.TC_TerritorryManagerTasks">
        <test-method status="PASS" signature="TC001_Verify_Navigate_TO_Territorry_Manager_Task()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC001_Verify_Navigate_TO_Territorry_Manager_Task" duration-ms="6974" started-at="2019-01-23T18:02:03Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Verify_Navigate_TO_Territorry_Manager_Task -->
        <test-method status="FAIL" signature="TC_002_verify_User()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_002_verify_User" duration-ms="47" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [supun_zincat] but found [Supun_zincat]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [supun_zincat] but found [Supun_zincat]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.TerritorryManagerTasks.VerifyText(TerritorryManagerTasks.java:55)
	at pages.TerritorryManagerTasks.VeriUsername(TerritorryManagerTasks.java:61)
	at testCases.TC_TerritorryManagerTasks.TC_002_verify_User(TC_TerritorryManagerTasks.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_verify_User -->
        <test-method status="PASS" signature="TC_003_verify_header_text()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_003_verify_header_text" duration-ms="73" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_verify_header_text -->
        <test-method status="PASS" signature="TC_004_verify_Start_From_Date_Text()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_004_verify_Start_From_Date_Text" duration-ms="51" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_004_verify_Start_From_Date_Text -->
        <test-method status="PASS" signature="TC_005_verify_End_Date_text()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_005_verify_End_Date_text" duration-ms="38" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_005_verify_End_Date_text -->
        <test-method status="PASS" signature="TC_006_verify_Territory_Text()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_006_verify_Territory_Text" duration-ms="59" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_006_verify_Territory_Text -->
        <test-method status="PASS" signature="TC_007_verify_Status_Text()[pri:0, instance:testCases.TC_TerritorryManagerTasks@69997e9d]" name="TC_007_verify_Status_Text" duration-ms="47" started-at="2019-01-23T18:02:10Z" finished-at="2019-01-23T18:02:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_007_verify_Status_Text -->
      </class> <!-- testCases.TC_TerritorryManagerTasks -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
