<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13635" started-at="2019-09-18T11:46:45Z" finished-at="2019-09-18T11:46:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13635" started-at="2019-09-18T11:46:45Z" finished-at="2019-09-18T11:46:58Z">
      <class name="testCases.TS_008_SummaryReport">
        <test-method status="PASS" signature="TC_001_verify_User_Able_TO_Navigate_Dashboard()[pri:0, instance:testCases.TS_008_SummaryReport@1b2abca6]" name="TC_001_verify_User_Able_TO_Navigate_Dashboard" is-config="true" duration-ms="6372" started-at="2019-09-18T17:16:45Z" finished-at="2019-09-18T17:16:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_verify_User_Able_TO_Navigate_Dashboard -->
        <test-method status="PASS" signature="TC_002_verify_SubTaskDetailedReport()[pri:0, instance:testCases.TS_008_SummaryReport@1b2abca6]" name="TC_002_verify_SubTaskDetailedReport" duration-ms="6097" started-at="2019-09-18T17:16:51Z" finished-at="2019-09-18T17:16:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_verify_SubTaskDetailedReport -->
        <test-method status="PASS" signature="TC_002_verify_Page_Name()[pri:0, instance:testCases.TS_008_SummaryReport@1b2abca6]" name="TC_002_verify_Page_Name" duration-ms="575" started-at="2019-09-18T17:16:57Z" finished-at="2019-09-18T17:16:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_002_verify_Page_Name -->
        <test-method status="FAIL" signature="TC_003_verify_User_name()[pri:0, instance:testCases.TS_008_SummaryReport@1b2abca6]" name="TC_003_verify_User_name" duration-ms="560" started-at="2019-09-18T17:16:58Z" finished-at="2019-09-18T17:16:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Supun_zinct] but found [Supun_zincat]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Supun_zinct] but found [Supun_zincat]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.VerifyTextgloble(verifications.java:32)
	at pages.SubTaskDetailedReport.verifyUsername(SubTaskDetailedReport.java:38)
	at testCases.TS_008_SummaryReport.TC_003_verify_User_name(TS_008_SummaryReport.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_003_verify_User_name -->
      </class> <!-- testCases.TS_008_SummaryReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
